### ISSUE TITLE
Replace vue-cli with vite

### ISSUE THREAD

**Issue by jaythomas** [JTCC-Programming-Club/website#19]
[vue-cli is now in maintenance mode](https://github.com/vuejs/vue-cli#%EF%B8%8F-status). There's a new node module for bundling frontend apps and running local dev server that is vue/framework-agnostic called Vite: https://vitejs.dev/

Aside from being a better tool overall, the fact it can bootstrap and run web applications not built on vue (or built on other frameworks) makes it more versatile for use elsewhere.

**Comment by jaythomas** [comment]
This update would also make redundant security alerts [we're receiving from dependabot](https://github.com/codi-hacks/website/security/dependabot) about outdated node modules being pulled in by vue-cli.

**Comment by wyatt-herkamp** [comment]
I can take care of this once I finish updating some lockfree library
